name: CI

on:
  push:
    branches-ignore:
      - main
      - alpha
      - beta
    tags-ignore:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn --frozen-lockfile

      - name: Lint, typecheck and test
        run: |
          yarn ci-test
